import PDFDocument from 'pdfkit';
import { config } from '../config/env.js';
import { logger } from '../utils/logger.js';

const formatCurrency = (amount, currency = 'USD') =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency,
    currencyDisplay: 'symbol',
  }).format(amount || 0);

const formatDate = (value) => {
  if (!value) return '—';
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? '—' : date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
};

export const generateReceiptPdfBuffer = async ({ invoice, client, company = {} }) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 44 });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (error) => reject(error));

      const companyName = company.name || 'VaultPay Financial Core';
      const companyEmail = company.email || 'support@vaultpay.example';
      const companyAddress = company.address || '1 Financial Plaza, New York, NY';
      const receiptNumber = `RCPT-${invoice.invoiceNumber || invoice._id?.toString() || 'N/A'}`;
      const paymentMethod = invoice.paymentMethod || 'Card';
      const paymentStatus = invoice.status === 'paid' ? 'PAID' : 'PENDING';

      doc
        .font('Helvetica-Bold')
        .fontSize(20)
        .text(companyName, { align: 'left' })
        .font('Helvetica')
        .fontSize(10)
        .fillColor('#64748b')
        .text(companyEmail, { align: 'left' })
        .text(companyAddress, { align: 'left' });

      doc.moveDown(0.5);
      doc.rect(40, 110, 515, 96).fillAndStroke('#f8fafc', '#e2e8f0');
      doc.fillColor('#0f172a');
      doc.font('Helvetica-Bold').fontSize(16).text('Payment Receipt', 60, 128);
      doc.font('Helvetica').fontSize(11).text(`Receipt Number: ${receiptNumber}`, 60, 152);
      doc.text(`Invoice Number: ${invoice.invoiceNumber || '—'}`, 60, 168);
      doc.text(`Issued: ${formatDate(invoice.createdAt)}`, 60, 184);
      doc.text(`Paid: ${formatDate(invoice.paidAt || invoice.updatedAt)}`, 330, 184);

      doc.moveDown(1.7);
      doc.font('Helvetica-Bold').fontSize(12).text('Bill To', 40, 240);
      doc.font('Helvetica').fontSize(11);
      doc.text(client?.name || 'Client', 40, 258);
      doc.text(client?.email || 'client@example.com', 40, 274);
      if (client?.billingAddress) {
        doc.text(client.billingAddress, 40, 290);
      }

      doc.fillColor('#166534');
      doc.font('Helvetica-Bold').fontSize(18).text(paymentStatus, 430, 248, { align: 'right' });
      doc.fillColor('#0f172a');

      doc.moveTo(40, 330).lineTo(555, 330).stroke();
      doc.moveDown(0.6);
      doc.font('Helvetica-Bold').fontSize(11).text('Description', 40, 344);
      doc.text('Qty', 320, 344);
      doc.text('Unit Price', 395, 344);
      doc.text('Amount', 485, 344, { align: 'right' });
      doc.moveTo(40, 360).lineTo(555, 360).stroke();

      const items = Array.isArray(invoice.items) ? invoice.items : [];
      let y = 372;
      items.forEach((item) => {
        doc.font('Helvetica').fontSize(10);
        doc.text(item.description || 'Item', 40, y, { width: 250 });
        doc.text(String(item.quantity || 0), 320, y);
        doc.text(formatCurrency(item.unitPrice || 0, invoice.currency), 395, y);
        doc.text(formatCurrency(item.amount || 0, invoice.currency), 485, y, { align: 'right' });
        y += 20;
        if (y > 640) {
          doc.addPage();
          y = 60;
        }
      });

      doc.moveTo(40, y + 12).lineTo(555, y + 12).stroke();
      doc.font('Helvetica').fontSize(10);
      doc.text('Subtotal', 395, y + 28);
      doc.text(formatCurrency(invoice.subtotal || 0, invoice.currency), 485, y + 28, { align: 'right' });
      doc.text('Tax', 395, y + 46);
      doc.text(formatCurrency(invoice.tax || 0, invoice.currency), 485, y + 46, { align: 'right' });
      doc.font('Helvetica-Bold').fontSize(12);
      doc.text('Grand Total', 395, y + 66);
      doc.text(formatCurrency(invoice.total || 0, invoice.currency), 485, y + 66, { align: 'right' });

      doc.font('Helvetica').fontSize(10).fillColor('#64748b');
      doc.text(`Currency: ${invoice.currency || 'USD'}`, 40, y + 90);
      doc.text(`Transaction ID: ${invoice.stripePaymentIntentId || 'N/A'}`, 40, y + 108);
      doc.text(`Stripe Payment Intent ID: ${invoice.stripePaymentIntentId || 'N/A'}`, 40, y + 126);

      doc.rotate(-20, { origin: [280, 420] });
      doc.font('Helvetica-Bold').fontSize(48).fillColor('rgba(15, 23, 42, 0.08)').text('PAID', 120, 360);
      doc.rotate(20, { origin: [280, 420] });

      doc.font('Helvetica').fontSize(9).fillColor('#64748b');
      doc.text(`Generated by ${companyName} • ${config.app.serverUrl}`, 40, 760, { align: 'left' });
      doc.text('Thank you for choosing VaultPay.', 480, 760, { align: 'right' });

      doc.end();
    } catch (error) {
      logger.error(`Receipt PDF generation failed: ${error.message}`);
      reject(error);
    }
  });
};
